### ISSUE TITLE
Add react-addons-pure-render-mixin

### ISSUE THREAD

**Issue by mauron85** [preact-compat/react#1]
Modules that have react-addons-pure-render-mixin as dependencies will fail to build with webpack.

```
ERROR in ./~/react-addons-pure-render-mixin/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactComponentWithPureRenderMixin' in /home/mauron85/../node_modules/react-addons-pure-render-mixin
 @ ./~/react-addons-pure-render-mixin/index.js 1:17-71
webpack built d3fa4c83b55a2b87fd82 in 16337ms
```
This is issue is same as [preact-compat issue #254](https://github.com/developit/preact-compat/issues/254)

**Comment by iamale** [comment]
GitHub didn't close this automatically for some reason, huh
